افزودن مستند پروژه نهایی
MARS-JSU/Internship-Documents pull request #15
Opened 2021-10-10 20:22 UTC by RAAvenger

2021-10-11 06:58 UTC, MRAmeli requested changes

2021-10-11 06:58 UTC, MRAmeli commented on General Docs/FinalPhase-ChatHouse/readme.md
> +همانطور که بالاتر اشاره شد کاربر ایجاد کننده اتاق به عنوان مدیر اتاق دسترسی‌هایی فراتر از سایر اعضای اتاق دارد، از جمله این دسترسی‌ها می‌توان به تغییر مشخصات اتاق( نام، وضعیت عمومی/خصوصی بودن و توضیح
```suggestion
همانطور که بالاتر اشاره شد کاربر ایجاد کننده اتاق به عنوان مدیر اتاق دسترسی‌هایی فراتر از سایر اعضای اتاق دارد، از جمله این دسترسی‌ها می‌توان به تغییر مشخصات اتاق( نام، وضعیت عمومی/خصوصی بودن و توضیحات )، ویرایش کلید اتاق خصوصی( کلید اولیه به صورت خودکار ساخته شود، همچنین مدیر اتاق می‌تواند از امکان تولید کلید خودکار در هنگام ویرایش کلید استفاده کند )، حذف اعضا از اتاق، حذف اتاق و دریافت گزارشی شامل تعداد ‌پیام‌های ارسال شده توسط هر عضو به صورت csv و pdf اشاره کرد.
```

2021-10-11 06:58 UTC, MRAmeli commented on General Docs/FinalPhase-ChatHouse/readme.md
> +در این سایت مفهومی به نام مدیرکل داریم که در همه اتاق‌ها دسترسی مدیریت دارد و قادر است به اتاق‌های خصوصی بدون وارد کردن رمز عبور وارد شود. همچنین مدیرکل امکان مشاهده گزارشاتی مانند درصد فعالیت کلیه ا
```suggestion
در این سایت مفهومی به نام مدیرکل داریم که در همه اتاق‌ها دسترسی مدیریت دارد و قادر است به اتاق‌های خصوصی بدون وارد کردن رمز عبور وارد شود. همچنین مدیرکل امکان مشاهده گزارشاتی مانند درصد فعالیت کلیه اتاق‌ها در بازه‌های زمانی( یک نمودار کیکی که در بازه زمانی مشخص شده درصد پیام‌های ارسالی هر اتاق نسبت به کل پیام‌های ارسال شده در آن بازه زمانی را نمایش می‌دهد ) و امکان مشاهده کلیه پیام‌های ارسال شده در سامانه طی یک بازه زمانی( یک نمودار خطی-زمانی که پیام‌های ارسال شده طی بازه زمانی را به تفکیک روز نمایش می‌دهد ) را دارد. همچنین مدیر کل امکان اخراج یک کاربر از کل سایت را نیز دارد.
```

2021-10-11 06:58 UTC, MRAmeli commented on General Docs/FinalPhase-ChatHouse/readme.md
> +![chart1](https://github.com/MARS-JSU/Internship-Documents/blob/main/General%20Docs/FinalPhase-ChatHouse/chart1.jpg )
عکس ها مشکل دارن.

2021-10-13 06:40 UTC, RAAvenger commented on General Docs/FinalPhase-ChatHouse/readme.md
> +![chart1](https://github.com/MARS-JSU/Internship-Documents/blob/main/General%20Docs/FinalPhase-ChatHouse/chart1.jpg )
بایدبرن روی برنچ مستر تا نمایش داده بشن

2021-10-17 06:56 UTC, merged