Mobile
MARS-JSU/Internship-Documents pull request #2
Opened 2021-07-24 03:08 UTC by MRAmeli

2021-07-24 14:07 UTC, RAAvenger requested changes

2021-07-24 14:07 UTC, RAAvenger commented on Mobile Docs/Phase01-Dart/readme.md
> +دارت زبانی برپایه کلاس، وراثت یگانه و شی گرایی است که گرامر آن شبیه زبان C بوده و دارای Interface،reified generics کلاسهای Abstract و Optional typing می‌باشد. type annotationهای ایستا تأثیری بر روی س
<div dir="rtl">
اصلاح شده:
 دارای Interface ،reified generics، کلاس‌های Abstract و Optional typing می‌باشد.


امکانش هست که توی پرانتز برای این واژه‌های انگلیسی( به جز interface ) معادلی توی پرانتز بنویسی؟

2021-07-24 14:07 UTC, RAAvenger commented on Mobile Docs/Phase01-Dart/readme.md
> +
<div dir="rtl">

به نظرم از « type annotationهای ایستا تأثیری بر روی سمانتیک» به بعد توضیحات اضافیه و فقط بچه‌ها رو گیج میکنه.

2021-07-24 14:07 UTC, RAAvenger commented on Mobile Docs/Phase01-Dart/readme.md
> +### مدهای زمان‌های اجرا
مدهای زمان اجرا رو لازمه توی متن __آشنایی با زبان دارت__ بخونن؟

2021-07-24 14:07 UTC, RAAvenger commented on Mobile Docs/Phase01-Dart/readme.md
> +
یکم این تیکه اصلاحات نگارشی میخواد، مثلا زمان فعل توی جمله اخر با جمله قبلش فرق میکنه در حالی که دوتا جمله درباره‌ی یک کامپایلر هستن.

البته شاید هم من بد فهمیدم.

2021-07-24 14:07 UTC, RAAvenger commented on Mobile Docs/Phase01-Dart/readme.md
> +برای نوشتن کد به زبان دارت مانند سایر زبان‌های برنامه نویسی به یک محیط توسعه( IDE ) نیاز دارید که IDE پیشنهادی ما [VSCode](https://code.visualstudio.com/) می‌باشد. در کنار IDE برای اجرای کدهای زبان د
اگر میشه صرفا یه اشاره‌ی کوچیکی بکن که با اندروید استودیو هم میتونن بنویسن. صرفا برای اینکه یه آپشن دوم داشته باشن و یا اگر از قبل اندروید استودیو دارن فکر نکنن با اون نمیشه کار کرد دیگه.

2021-07-24 19:16 UTC, MRAmeli commented on Mobile Docs/Phase01-Dart/readme.md
> +دارت زبانی برپایه کلاس، وراثت یگانه و شی گرایی است که گرامر آن شبیه زبان C بوده و دارای Interface،reified generics کلاسهای Abstract و Optional typing می‌باشد. type annotationهای ایستا تأثیری بر روی س
<div dir="rtl" align='right'>
اوکیه :+1: 

عبارت reified generics رو حذف میکنم، چون به نظرم بچه ها رو گیج میکنه.

2021-07-24 19:30 UTC, MRAmeli commented on Mobile Docs/Phase01-Dart/readme.md
> +
<div dir="rtl" align='right'>

به نظرم فعل جمله آخر مشکلی نداره ولی در کل جمله‌بندیاش خوب نبود، بهترشون کردم.

2021-07-24 20:06 UTC, MRAmeli commented on Mobile Docs/Phase01-Dart/readme.md
> +برای نوشتن کد به زبان دارت مانند سایر زبان‌های برنامه نویسی به یک محیط توسعه( IDE ) نیاز دارید که IDE پیشنهادی ما [VSCode](https://code.visualstudio.com/) می‌باشد. در کنار IDE برای اجرای کدهای زبان د
<div dir="rtl" align='right'>

برای کار کردن با زبان دارت AndroidStudio پیشنهاد نمیشه، اما برای فلاتر اوکیه، برسن به فاز فلاتر بشون میگم.

برای آپشن دوم برای دارت خود بچه های دارت IntelliJ IDEA رو پیشنهاد دادن، اضافش میکنم.

2021-07-24 20:10 UTC, MRAmeli commented on Mobile Docs/Phase01-Dart/readme.md
> +### مدهای زمان‌های اجرا
<div dir="rtl" align='right'>

درسته مربوط به آشنایی با خود زبان نیست، ولی متاسفانه داخل داکیومنت های آموزش چیزی درموردش نمیگن. 

چون اهمیتشم اونقدر زیاد نیست پاکش میکنم.

2021-07-25 04:42 UTC, RAAvenger approved these changes

2021-08-06 07:11 UTC, merged